### ISSUE TITLE
create-tarball should accept have a parameter to limit the number of days

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/puppetlabs-puppet_metrics_collector#18]
The `/opt/puppetlabs/bin/puppet-metrics-collector create-tarball` script is a great way to collect the metrics in a tarball. It would be nice to have an optional parameter to limit the number of days to collect and default to the `puppet_metrics_collector::retention_days`.

**Comment by tkishel** [comment]
Would be resolved via #47 in files/create-metrics-archive

**Comment by jarretlavallee** [comment]
Merged
