### ISSUE TITLE
Problem with Collecting the whole Data with PE installation type 3-Way Split

### ISSUE THREAD

**Issue by MCKerb** [puppetlabs/puppetlabs-puppet_metrics_collector#24]
## Use Case
The json-files are collected on each server (MoM, PuppetDB, Orchestrator and the Compile Masters) we are using. How can we collect every json-file centrally on the MoM.

## Describe the Solution You Would Like
Collecting every json-file on the MoM

**Comment by tkishel** [comment]
When you apply the `puppet_metrics_collector` class to the Master, it should collect metrics from the services (PuppetDB, PuppetServer) other the hosts (PuppetDB, Compilers) and store them on the Master, as per:

https://forge.puppet.com/puppetlabs/puppet_metrics_collector#setup

Please verify that you are using the current version (5.3.0) of the module, and have applied the `puppet_metrics_collector` class only to the Master.

**Comment by tkishel** [comment]
Closing as inactive.
