### ISSUE TITLE
Collect PostgreSQL metrics, like the puppet_metrics_dashboard does

### ISSUE THREAD

**Issue by tkishel** [puppetlabs/puppetlabs-puppet_metrics_collector#34]
## Use Case
The puppet_metrics_dashboard collects and displays valuable PostgreSQL metrics, this could too.

## Describe the Solution You Would Like
Try to reuse puppet_metrics_dashboard code.

PostgreSQL 11 may have additional built-ins related to this.

**Comment by tkishel** [comment]
Access:

https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/manifests/profile/master/postgres_access.pp

Collect:

https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/manifests/profile/master/postgres.pp

... or this remarkably similar template, though I don't see where "telegraf.conf.epp" is referenced in code:

https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/templates/telegraf.conf.epp

**Comment by jarretlavallee** [comment]
Resolved by #71

**Comment by tkishel** [comment]
Yay!
