### ISSUE TITLE
json2timeseries removes service prefix from orchestrator and puppetdb metrics

### ISSUE THREAD

**Issue by tkishel** [puppetlabs/puppetlabs-puppet_metrics_collector#40]
In `influx_tag_parser` in `json2timeseries` ...

```
  if tag.include? 'orchestrator'
    tag_set = "#{tag_set}service=orchestrator,"
    tag.delete('orchestrator')
  end

  if tag.include? 'puppetdb'
    tag_set = "#{tag_set}service=puppetdb,"
    tag.delete('puppetdb')
  end
```

Resulting in Puppet Server metrics being prefixed when imported:

```
puppetserver.jvm-metrics.heap-memory ...
```

But the other two are "bare":

```
jvm-metrics.heap-memory ...
```

The PuppetDB dashboards in Puppet Metrics Dashboard accommodate those "bare" metrics.
Shouldn't all metrics be prefixed?

If so, can we fix this here and in the PuppetDB dashboards in Puppet Metrics Dashboard?

(Especially before we create Orchestrator dashboards.)

**Comment by RandellP** [comment]
already working on this (discussed with Tom offline).  Will bring new graphs and such to ref arch meeting for feedback.
