### ISSUE TITLE
Requesting that telegraf be an option to send metrics to

### ISSUE THREAD

**Issue by patrickmayes** [puppetlabs/puppetlabs-puppet_metrics_collector#41]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [ I would like the ability to send metrics off to an existing Telegraf instance ]

## Describe the Solution You Would Like
I would like integration to send off my metrics to Telegraf without having to come up with a toolset myself that will do this.

## Describe Alternatives You've Considered
We have thought about creating a tool that would pull in the data and send it off to telegraf, however we really would like this to be an option in the module itself.

## Additional Context
We have a Telegraf instance already, and don't want to setup a telegraf/graphite dashboard on my puppet servers to transfer the data from said dashboard to Telegraf as that does not seem as a great pathway forward.  We would be creating a dashboard that no one would look at, and it would just be there for the purpose to send data off to the Enterprise standard Telegraf servers.

**Comment by jarretlavallee** [comment]
@patrickmayes Do you use InfluxDB as the data storage? We can ship metrics to InfluxDB, Splunk HEC, and Graphite natively in this module. https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector#metrics-server-parameters

If you are looking to configure telegraf to ship the metrics to a different backend database, you could look at https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/manifests/telegraf/config.pp where we configure telegraf to pull metrics from the Puppet Services. It will likely not work as is, but you could raise a feature request in that repo for the metrics configuration to be separated from the telegraf installation.

**Comment by patrickmayes** [comment]
@jarretlavallee It does turn out that our setup is using the InfluxDB as the datastore and looking at the telegraf config it shows everything except for the **metrics_server_db_name** in a conf that we're looking at.  It would be nice in the instructions of the module on ways to identify the information and mention that influxdb can be used for the telegraf configuration.

**Comment by tkishel** [comment]
This module and Telegraf perform the same function: they both collect and send the data to a database or filesystem. Rather, you should choose either to use this module to collect and send data to your database; or use Telegraf to collect and send data to your database.

**Comment by jarretlavallee** [comment]
Closing as this module has the ability to ship metrics. Please open a new issue if there is another database you would like to see this module ship metrics to.
