### ISSUE TITLE
(SUP-2736)Update puppet strings docs

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/puppetlabs-puppet_metrics_collector#55]
## Use Case
The `REFERENCE.md` is a helpful document that will enable better use of the module. This file is automatically included on the Puppet forge. The file can be automatically generated when there is documentation in the code, but this is missing. 

## Describe the Solution You Would Like
Update the code to have puppet-strings docs <https://puppet.com/blog/using-puppet-strings-generate-great-documentation-puppet-modules/>

## Additional Context
Future builds can automatically generate the `REFERENCE.md` with `bundle exec rake strings:generate:reference`

**Comment by MartyEwings** [comment]
@jarretlavallee with recent releases we are automatically generating this do we see this as complete

https://forge.puppet.com/modules/puppetlabs/puppet_metrics_collector/reference

However it's mostly descriptions  of the mechanics of the parameters as the module doesn't seem to have wordy descriptions

**Comment by jarretlavallee** [comment]
Thanks @MartyEwings The request here is to update the documentation code so that the REFERENCE.md has better descriptions of what the parameters, functions, etc do.

**Comment by MartyEwings** [comment]
Strings is at 100%
