### ISSUE TITLE
Errors from cron jobs after upgrade to PE 2021.0

### ISSUE THREAD

**Issue by hawkeye-7** [puppetlabs/puppetlabs-puppet_metrics_collector#81]
## Describe the Bug
Errors from cron jobs after upgrade to PE 2021.0

## Steps to Reproduce
Upgraded to PE 2021.0

/opt/puppetlabs/puppet-metrics-collector/scripts/pe_metrics.rb:134:in `block in retrieve_additional_metrics': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/puppetlabs/puppet-metrics-collector/scripts/pe_metrics.rb:131:in `each_index'
	from /opt/puppetlabs/puppet-metrics-collector/scripts/pe_metrics.rb:131:in `retrieve_additional_metrics'
	from /opt/puppetlabs/puppet-metrics-collector/scripts/tk_metrics:29:in `block in <main>'
	from /opt/puppetlabs/puppet-metrics-collector/scripts/tk_metrics:17:in `each'
	from /opt/puppetlabs/puppet-metrics-collector/scripts/tk_metrics:17:in `<main>'

## Environment
RedHat 7.0

**Comment by jarretlavallee** [comment]
Thank you for reporting this @hawkeye-7. I was able to reproduce this with the `puppetdb` metrics on PE 2021.
